language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Mnnk9HBNeQmZqqwi9C5hKP2O6ZK7/5w/z5MP/LwDpr+gICV1ugkaQc5smpeMOU0KpfwzBYrArrhS7gXoSK5+4PJuqodULHxQFn5lrZPeL89X7/3ZQS0yCBWTGmzBbZldUNoHR/GtyukTFnGdh80A2merGfPQJRmUhcMtM+jxvOeY20vUxFF1ubaKuAScBP5JwW4Z56WhJVNwQOuFfHMIk9f175iqDSqdWvroqBtCHX1bQQeO5VUNYKoiUSW042bgc8Porep/yNO1FPIbZAPVU3W7g26eTn9CKvf5UpqZPrGp4CV04OftvLC6MoxlAHxvlQuQCPJMzq0tT9fvTBjg4mRSPd0fwMvLwB7fm+SlzH+Fp/Ea1j5vjKJGb/70OcsyK7usLZXi7uQUlm0zmlRMHHPB4HwsDKrdPDo6aMnNlN32IuBpbAnG7dFdOyFcNnaDzEjpjoYWWxnav1+dq0ks/AZlPNwu8E3g5Y6rV8zoUuQXo7uyRMUD328tfmxeTjlNb4adpF8YdPWp6bJPQ8DZJZSbRXtMWX7ZZqAPk/94IiYUEhbmmabWv86dUFXk43FzPSh1EQWoAHY+7tcwQc3rL+OeXC3rTS7EAnoOrX5CrQnVCoz04DlRI/gbZTwp8ukTklMTE1engmtAU9VIh1c4eYuVcJbUqrMhB9qzCD5zt+M="
env:
  secure: "JgyA9pVTLwM89Y4u6mKhyuek9DbWBK/VkeWy7vWLmvcyYDSEOhR/8VOOe1SDvQEZ0YOv93/KlIa1quwQvst05+mpKxQez0vUuf7q6GPRpcTTcS4JNy18qfQOLZ+Dq9IBnJ58gZIh4SIZylqALlXUPbqQJ+w/n4Wv4kWQ4N/0CmRgmRdGl4bcwAb5SBO/95xjTRyDGaj9zFQNOy7pZrWzzmAhZtCyYvj12Gs53rJ760jRkRmPL3cIwdF+VH8aqtCphbsDXdLBd8x/yjciQ1JB5TUsk3EqF29tQMtP3/ecYK+8AbdY/7WVZcTSew7iPpdiwuew3TGUtwtH4kkNmWaqwAWwenY7bUrygLGdUcSGlEw+S0uoV7wXUv5zkjvYo2CmE7+fNUO4oVzmohV3ggzWbBWbMDv4QMraHCvk+74AgGDmWWKqwdhPYm6lwgQKnoClCFN0OpAZ9jlQMIm1v37X6C3a0xUz5QCns1Kk7+YbXIupFEWZk4RMu8xbVQJ644wMs7bzd+3i9OLfniDHVNIQLRS0eu2IXwsNFmpYCn6FaS2mWDMYylpmTDcG5jZBjSjaQ+PJ/rdUydymAwyft8G8kHnk8vDG/VSmbT+jOvceUkFurUj+cYKv5Uk9CI0AfVcs08ivLj29o5LEqT61N65O8+wsff/JAkxXcUhzwV0ccQ8="
