language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install fur -g
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Mnnk9HBNeQmZqqwi9C5hKP2O6ZK7/5w/z5MP/LwDpr+gICV1ugkaQc5smpeMOU0KpfwzBYrArrhS7gXoSK5+4PJuqodULHxQFn5lrZPeL89X7/3ZQS0yCBWTGmzBbZldUNoHR/GtyukTFnGdh80A2merGfPQJRmUhcMtM+jxvOeY20vUxFF1ubaKuAScBP5JwW4Z56WhJVNwQOuFfHMIk9f175iqDSqdWvroqBtCHX1bQQeO5VUNYKoiUSW042bgc8Porep/yNO1FPIbZAPVU3W7g26eTn9CKvf5UpqZPrGp4CV04OftvLC6MoxlAHxvlQuQCPJMzq0tT9fvTBjg4mRSPd0fwMvLwB7fm+SlzH+Fp/Ea1j5vjKJGb/70OcsyK7usLZXi7uQUlm0zmlRMHHPB4HwsDKrdPDo6aMnNlN32IuBpbAnG7dFdOyFcNnaDzEjpjoYWWxnav1+dq0ks/AZlPNwu8E3g5Y6rV8zoUuQXo7uyRMUD328tfmxeTjlNb4adpF8YdPWp6bJPQ8DZJZSbRXtMWX7ZZqAPk/94IiYUEhbmmabWv86dUFXk43FzPSh1EQWoAHY+7tcwQc3rL+OeXC3rTS7EAnoOrX5CrQnVCoz04DlRI/gbZTwp8ukTklMTE1engmtAU9VIh1c4eYuVcJbUqrMhB9qzCD5zt+M="
